### ISSUE TITLE
Constrain permission scope

### ISSUE THREAD

**Issue by gene1wood** [hackmdio/hackmd-it-issues#1]
Currently the HackMD add-on requests a broad scope of permissions, likely broader than it needs.

![hackmd-add-on-permission-scopes](https://user-images.githubusercontent.com/1134034/39710037-7f30bf2a-51d0-11e8-98de-2c9b7ac86926.png)

Can you constrain this to only GitHub domains (or the domains of the sites on which the add-on functions)?

@GitOnion and I chatted about this on Friday but I thought I would capture it in an issue for good measure.

**Comment by jackycute** [comment]
Thank you @gene1wood 
I would assign this to our current extension maintainer @Yukaii

**Comment by Yukaii** [comment]
This is fixed in our latest release 🎉 

Read our release note [here](https://hackmd.io/s/hackmd-it-release-notes) 😄
