### ISSUE TITLE
Cannot remove default template

### ISSUE THREAD

**Issue by banderlog** [hackmdio/hackmd-it-issues#19]
![image](https://github.com/hackmdio/hackmd-it-issues/assets/2557965/c9cd97c3-bdcd-4d7c-bb9e-bfd662caa126)

Cannot remove this looking-as-a-template-not-markdown-stuff, have 'There is no default note template.' in settings.

**Comment by jackycute** [comment]
close for now, feel free to open another one if this can be reproduced, please also attach OS version and browser version.
